package src.consts;

public enum ReaderResponses {
    FINISHED_READING,
    SKIPPED,
    OPENNING_BRACKET,
    CLOSING_BRACKET,
    READ_INTEGER,
    READ_STRING,
    READ_VARIABLE,
    READ_BINOP,
    ERROR_VAR_STARTS_WITH_DIGITS,
    ERROR_UNKNOWN_CHAR,
    ERROR_AFTER_VARIABLE,
    ERROR_STRING_DOESNT_END,
}
